a = input("Введите дату:")
b = input("Введите задачу:")
c = input("Введите дату:")
d = input("Введите задачу:")
e = input("Введите дату:")
f = input("Введите задачу:")
g = (a + " " + b)
z = (c + " " + d)
x = (e + " " + f)
print(g)
print(z)
print(x)
